//- React icons
export { BiHeart as Favorite } from "react-icons/bi"
export { FaFacebook as Facebook } from "react-icons/fa"
export { FaInstagram as Instagram } from "react-icons/fa"
export { FaTruck as Truck } from "react-icons/fa"
export { FaXTwitter as X } from "react-icons/fa6"
export { FaYoutube as Youtube } from "react-icons/fa"
export { MdOutlineFilterAlt as Filter } from "react-icons/md"
export { MdOutlineFilterAltOff as Unfilter } from "react-icons/md"
export { RxLapTimer as Stopwatch } from "react-icons/rx"
export { TbCreditCard as CreditCard } from "react-icons/tb"
export { TbFilterX as RemoveFilter } from "react-icons/tb"
