//- React
import React from "react"

//- Next
import type { Metadata } from "next"

//- Components
import Header from "@/components/Header"

export const metadata: Metadata = {
	authors: {
		name: "Matheus Zanela Picoli",
		url: "https://github.com/matheuszpicoli"
	},
	creator: "Matheus Zanela Picoli",
	title: "MP Sneakers"
	// description: "Generated by create next app",
}

interface RootLayoutProps {
	children: React.ReactNode
}

export function RootLayout<T extends RootLayoutProps>(props: Readonly<T>): React.JSX.Element {
	return (
		<html lang="pt-br">
			<body>
				<header>
					<Header />
				</header>
				<main>
					{props.children}
				</main>
			</body>
		</html>
	)
}

export default RootLayout
