//- React
import React from "react"

//- Next
import type { Metadata } from "next"
import Head from "next/head"

export const metadata: Metadata = {
	authors: {
		name: "Matheus Zanela Picoli",
		url: "https://github.com/matheuszpicoli"
	},
	creator: "Matheus Zanela Picoli",
	title: "MP Sneakers"
	// description: "Generated by create next app",
}

interface RootLayoutProps {
	children: React.ReactNode
}

export function RootLayout<T extends RootLayoutProps>(props: Readonly<T>): React.JSX.Element {
	return (
		<html lang="pt-br">
			<Head>
				<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
			</Head>
			<body>
				{props.children}
			</body>
		</html>
	)
}

export default RootLayout
